### ISSUE TITLE
Says Learn doesn't work, but it doesn

### ISSUE THREAD

**Issue by changamanda** [learn-co-curriculum/looping-break-gets#6]
anti bug report? Says you can't run Learn gem with gets.chomp. But it works fine with either rspec or learn.

**Comment by changamanda** [comment]
^Quote from a student

**Comment by loganhasson** [comment]
i can't get rspec to work either. the specs for this one aren't right i don't think. cc @jmburges

**Comment by AnnJohn** [comment]
Icebox for now

**Comment by adamjonas** [comment]
@AnnJohn This is a broken lab and should be of pretty high priority. It's on the public tracks and so it should be repaired as soon as possible.

**Comment by AnnJohn** [comment]
This seems to work. can someone post a screenshot of it not working.
![screen shot 2015-08-19 at 4 45 56 pm](https://cloud.githubusercontent.com/assets/1892150/9368557/e3d58e30-4691-11e5-8fd6-e610ced245cc.png)

**Comment by AnnJohn** [comment]
@adamjonas @loganhasson  see above comment

**Comment by loganhasson** [comment]
@AnnJohn @adamjonas my bad, looks like it does work. i can't remember which student was having an issue...i'll see if i can find the email exchange to find their exact PR...but their code seemed reasonable at the time and i couldn't get the spec suite to run. maybe an rspec/ruby version issue or something.

**Comment by adamjonas** [comment]
@loganhasson stop checking your email.

**Comment by sammarcus** [comment]
Just want to clarify, the workaround here is that the student mustn't call the method they've made. They simply need to define their method but not actually call it, as it will get stuck indefinitely on `gets` if it's ultimately called.

[`33da99c`](https://github.com/learn-co-curriculum/looping-break-gets/commit/33da99caadb3417f06d06505f8681a2d825d9fdc#diff-04c6e90faac2675aa89e2176d2eec7d8R141) reflects this, but not sure it's worded appropriately. Besides, if they can't run `learn` for both their local or remote build, the lab will never pass!

Alternatively, it could say something along the lines of "you should not be calling the `levitation_quiz` method you make after you define it in your solution. The `learn` gem does not work on solutions that call a method that has `gets.chomp` in it."

@SophieDeBenedetto the way the lab is written implies the student should call it right after they define it just as a means to test it, so maybe even simpler would be to just tell them to make sure their final solution doesn't call it?

I'll keep this closed and add to https://github.com/learn-co-curriculum/looping-break-gets/issues/4

see question student aksed [here](https://learn.co/tracks/web-development-fundamentals/intro-to-ruby/looping/looping-break-and-gets?batch_id=166&question_uid=q-4fe6c70a-1f68-4044-a2a6-b7082eb360db&track_id=10415)
